[package]
name = "dj-bot"
version = "1.0.0"
authors = ["Spencer <spencervess@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std", "process", "signal"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
uuid = "0.8"
sqlx = { git = "https://github.com/launchbadge/sqlx", rev = "af7f2594457e991fd84a97a2170f79801fbdf1df", features = ["runtime-tokio-rustls", "postgres", "offline"] }
anyhow = "1.0"
rand = "0.8"
lazy_static = "1.4"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
redis = { version = "0.19", features = ["tokio-comp"] }
sys-info = "0.7"
parking_lot = "0.11"
serenity = "0.10"
songbird = "0.1"
dashmap = "4.0.2"

[build-dependencies]
built = "0.4.4"
